import { CachedYouTubeData, YouTubeSubtitleItem } from '../types';

export const PRESET_YOUTUBE_DATA: Record<string, CachedYouTubeData> = {
  MiAl9CNZUuo: {
    version: 1,
    videoId: 'MiAl9CNZUuo',
    title: 'Nvidia CEO Jensen Huang Outlines AI Future As Global Economic Game Changer',
    duration: 89,
    captionSource: 'verified-bilingual-dataset',
    lastPlaybackPositionMs: 0,
    createdAt: 1789178692000,
    updatedAt: 1789178692000,
    subtitles: [
      {
        id: 'MiAl9CNZUuo-0',
        videoId: 'MiAl9CNZUuo',
        startMs: 0,
        endMs: 6500,
        english: 'Artificial intelligence represents the next fundamental infrastructure of the global economy, much like electricity and the internet.',
        traditionalChinese: '人工智慧代表了全球經濟的下一代基礎設施，正如電力與網際網路一樣。',
      },
      {
        id: 'MiAl9CNZUuo-1',
        videoId: 'MiAl9CNZUuo',
        startMs: 6500,
        endMs: 13500,
        english: 'Every country and every industry will need to build and operate their own AI infrastructure to power their local economies.',
        traditionalChinese: '每個國家和產業都需要建置並營運專屬的 AI 基礎設施，為在地經濟注入動能。',
      },
      {
        id: 'MiAl9CNZUuo-2',
        videoId: 'MiAl9CNZUuo',
        startMs: 13500,
        endMs: 20500,
        english: 'We are witnessing the beginning of a new industrial revolution where data and computation turn into digital intelligence.',
        traditionalChinese: '我們正見證一場新工業革命的序幕，數據與運算在此轉化為數位智慧。',
      },
      {
        id: 'MiAl9CNZUuo-3',
        videoId: 'MiAl9CNZUuo',
        startMs: 20500,
        endMs: 28500,
        english: 'The five-layer AI stack is transforming how companies operate, from energy and chips to infrastructure, models, and applications.',
        traditionalChinese: '五層 AI 架構正在重塑企業營運模式，涵蓋能源、晶片、基礎設施、模型乃至終端應用。',
      },
      {
        id: 'MiAl9CNZUuo-4',
        videoId: 'MiAl9CNZUuo',
        startMs: 28500,
        endMs: 36500,
        english: 'Rather than displacing workers, AI empowers people by automating routine tasks and supercharging individual productivity.',
        traditionalChinese: 'AI 並非取代勞工，而是透過自動化常規任務並倍增個人生產力來賦能人類。',
      },
      {
        id: 'MiAl9CNZUuo-5',
        videoId: 'MiAl9CNZUuo',
        startMs: 36500,
        endMs: 44500,
        english: 'In fields like healthcare, robotics, and scientific discovery, AI enables researchers to solve problems that were previously intractable.',
        traditionalChinese: '在醫療、機器人與科學探索等領域，AI 讓研究人員得以攻克以往難以解決的難題。',
      },
      {
        id: 'MiAl9CNZUuo-6',
        videoId: 'MiAl9CNZUuo',
        startMs: 44500,
        endMs: 52500,
        english: 'Countries that invest aggressively in sovereign AI capabilities today will secure their technological leadership for decades to come.',
        traditionalChinese: '當前積極投資主權 AI 能力的國家，將奠定未來數十年的科技領先地位。',
      },
      {
        id: 'MiAl9CNZUuo-7',
        videoId: 'MiAl9CNZUuo',
        startMs: 52500,
        endMs: 60500,
        english: 'We are building the AI factories of tomorrow, producing tokens of intelligence at the lowest possible cost and maximum efficiency.',
        traditionalChinese: '我們正在打造未來的 AI 工廠，以最低的成本與極致的效率產出智慧代幣。',
      },
      {
        id: 'MiAl9CNZUuo-8',
        videoId: 'MiAl9CNZUuo',
        startMs: 60500,
        endMs: 69500,
        english: 'Artificial general intelligence is no longer science fiction; it is becoming an everyday reality that will uplift every sector of society.',
        traditionalChinese: '通用人工智慧已不再是科幻情節，它正演變為提升社會各個領域的日常現實。',
      },
      {
        id: 'MiAl9CNZUuo-9',
        videoId: 'MiAl9CNZUuo',
        startMs: 69500,
        endMs: 78500,
        english: 'The opportunity before us is extraordinary, and everyone should embrace these tools to shape the future of work and innovation.',
        traditionalChinese: '我們眼前的機遇非比尋常，每個人都應擁抱這些工具，共同開創工作與創新的未來。',
      },
      {
        id: 'MiAl9CNZUuo-10',
        videoId: 'MiAl9CNZUuo',
        startMs: 78500,
        endMs: 88500,
        english: 'By democratizing access to computing and intelligence, we ensure that the benefits of this revolution reach all communities worldwide.',
        traditionalChinese: '透過運算與智慧的普及化，我們確保這場革命帶來的福祉能惠及全球所有社群。',
      },
    ],
  },
  UF8uR6Z6KLc: {
    version: 1,
    videoId: 'UF8uR6Z6KLc',
    title: 'Steve Jobs 2005 Stanford Commencement Address',
    duration: 904,
    captionSource: 'verified-bilingual-dataset',
    lastPlaybackPositionMs: 0,
    createdAt: 1789178692000,
    updatedAt: 1789178692000,
    subtitles: [
      {
        id: 'UF8uR6Z6KLc-0',
        videoId: 'UF8uR6Z6KLc',
        startMs: 0,
        endMs: 5000,
        english: 'I am honored to be with you today at your commencement from one of the finest universities in the world.',
        traditionalChinese: '今天我很榮幸能與各位齊聚一堂，參加世界上最頂尖大學之一的畢業典禮。',
      },
      {
        id: 'UF8uR6Z6KLc-1',
        videoId: 'UF8uR6Z6KLc',
        startMs: 5000,
        endMs: 11000,
        english: 'I never graduated from college. Truth be told, this is the closest I’ve ever gotten to a college graduation.',
        traditionalChinese: '我從未大學畢業。說實話，這是我這輩子離大學畢業典禮最近的一刻。',
      },
      {
        id: 'UF8uR6Z6KLc-2',
        videoId: 'UF8uR6Z6KLc',
        startMs: 11000,
        endMs: 17500,
        english: 'Today I want to tell you three stories from my life. That’s it. No big deal. Just three stories.',
        traditionalChinese: '今天我想與各位分享我生命中的三個故事。沒什麼大道理，就只是三個故事。',
      },
      {
        id: 'UF8uR6Z6KLc-3',
        videoId: 'UF8uR6Z6KLc',
        startMs: 17500,
        endMs: 22000,
        english: 'The first story is about connecting the dots.',
        traditionalChinese: '第一個故事是關於串連生命中的點滴。',
      },
      {
        id: 'UF8uR6Z6KLc-4',
        videoId: 'UF8uR6Z6KLc',
        startMs: 22000,
        endMs: 29000,
        english: 'I dropped out of Reed College after the first 6 months, but then stayed around as a drop-in for another 18 months or so before I really quit.',
        traditionalChinese: '我在里德學院讀了六個月後就退學了，但在真正徹底離開前，我又以旁聽生身分待了約十八個月。',
      },
      {
        id: 'UF8uR6Z6KLc-5',
        videoId: 'UF8uR6Z6KLc',
        startMs: 29000,
        endMs: 36000,
        english: 'You can’t connect the dots looking forward; you can only connect them looking backwards.',
        traditionalChinese: '你無法預先串連未來的點滴；你只能在回顧過往時才能將它們串聯起來。',
      },
      {
        id: 'UF8uR6Z6KLc-6',
        videoId: 'UF8uR6Z6KLc',
        startMs: 36000,
        endMs: 44000,
        english: 'So you have to trust that the dots will somehow connect in your future.',
        traditionalChinese: '因此你必須堅信，這些生命中的點滴未來一定會以某種方式連結在一起。',
      },
      {
        id: 'UF8uR6Z6KLc-7',
        videoId: 'UF8uR6Z6KLc',
        startMs: 44000,
        endMs: 53000,
        english: 'Your time is limited, so don’t waste it living someone else’s life. Stay hungry, stay foolish.',
        traditionalChinese: '你們的時間有限，所以切莫浪費時間去過他人的生活。保持飢渴，保持虛心。',
      },
    ],
  },
};
